### ISSUE TITLE
Make region's outline accessible through Python

### ISSUE THREAD

**Issue by RaphaelWimmer** [PDA-UR/Sketchable-Interaction#37]
Add field "self.outline" which returns a list of tuples representing coordinates (in absolute or relative coordinate system?). 
Field should be readable and writeable from Python code.

**Comment by HahnJuergen** [comment]
Instead of "self.outline" I used the term "self.shape". The shape is represented in absolute coordinates. If a region's shape is changed from within its effect, then "self.notify_shape_changed()" has to be called to register the geometry change of the region. Otherwise SIGRun **ignores** the coded change.
